app:
  name:    "customer-web-eapi"
  version: "1.0.0-SNAPSHOT"

api:
  groupId:      "${api.groupId}"
  artifactId:   "${api.artifactId}"
  version:      "${api.version}"
  majorVersion: "v1"

source: "Loves Travel Stop"
target: "SFDC"

https:
  host: "0.0.0.0"
  port: ""
  read:
    timeout: "80000"
  idle:
    timeout: "70000"

common:
  health:
    path: "/ready"
  ping:
    path: "/api/v1/ping"

method:
  retrieve: "GET"
  create: "POST"
  update: "PATCH"

papi:
  contacts:
    path: "/api/v1/contacts"
  accounts:
    path: "/api/v1/accounts"